#!/bin/bash

# inject a replacement "go binary" and update the path for the presentation
# this is required in order to make things like "go embed" work in the presentation
# due to the way that go present runs the code snippets
cat <<'EOGOFILE' > go
#!/bin/bash

if grep -q '^/tmp/' <<<$PWD; then
  rsync -ruhv --exclude="*.go" $REPO_DIR/ $PWD > /dev/null
  cp -r $REPO_DIR/go.mod $PWD/go.mod > /dev/null
fi

export GO111MODULE=auto

case $1 in
  build)
    $GO_ORIG_BIN $@ .
    ;;
  *)
    echo "Running $@"
    $GO_ORIG_BIN "$@"
    ;;
esac
EOGOFILE
chmod +x go

export GO_ORIG_BIN=$(which go)
export PATH=$PWD:$PATH
export REPO_DIR=$PWD
go run golang.org/x/tools/cmd/present@v0.21.0 -base=theme -use_playground=false "$@"
rm go
